/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.demokit.arquillian.calculator.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Calculator service. Represents a row in the &quot;MATH_CALCULATOR_Calculator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demokit.arquillian.calculator.model.impl.CalculatorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demokit.arquillian.calculator.model.impl.CalculatorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Calculator
 * @generated
 */
@ProviderType
public interface CalculatorModel extends BaseModel<Calculator> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a calculator model instance should use the {@link Calculator} interface instead.
	 */

	/**
	 * Returns the primary key of this calculator.
	 *
	 * @return the primary key of this calculator
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this calculator.
	 *
	 * @param primaryKey the primary key of this calculator
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this calculator.
	 *
	 * @return the uuid of this calculator
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this calculator.
	 *
	 * @param uuid the uuid of this calculator
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the calculator ID of this calculator.
	 *
	 * @return the calculator ID of this calculator
	 */
	public long getCalculatorId();

	/**
	 * Sets the calculator ID of this calculator.
	 *
	 * @param calculatorId the calculator ID of this calculator
	 */
	public void setCalculatorId(long calculatorId);

}